# star-bois dev server config
# Run with: make server-dev
#           make server-dev PRESET=Sandbox

[net]
tickrate = 30
port = 1212

[game]
hostname = "star-bois-dev"
lobbyenabled = true
lobbyduration = 5
map = "Cestoda"

[mcp]
enabled = true
port = 9222
client_url = "http://localhost:9223"

[starmap]
generate_roundstart = true

[warp]
instant_charge = true
